-- Drop the trigger and function
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();

-- Drop the user_profiles table
DROP TABLE IF EXISTS public.user_profiles;

-- Create users table for custom authentication
CREATE TABLE public.users (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  full_name TEXT NOT NULL,
  organization TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create index for faster username lookups
CREATE INDEX idx_users_username ON public.users(username);

-- Enable Row Level Security
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Policy: Anyone can read usernames (for login check)
CREATE POLICY "Anyone can check usernames" ON public.users
  FOR SELECT USING (true);

-- Policy: Anyone can insert (for registration)
CREATE POLICY "Anyone can register" ON public.users
  FOR INSERT WITH CHECK (true);

-- Add some pre-determined users (optional)
INSERT INTO public.users (username, password, full_name, organization) VALUES
  ('admin', 'admin123', 'Administrator', 'KhetScore Admin'),
  ('demo', 'demo123', 'Demo User', 'Demo Organization'),
  ('test', 'test123', 'Test User', 'Test Org');


-- =====================================================================
-- Farmers master data (loaded from farmerdata_prefill.csv)
-- =====================================================================

CREATE TABLE public.farmers (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  farmer_id       TEXT UNIQUE NOT NULL,    -- CSV: farmerID
  name            TEXT NOT NULL,           -- CSV: Name
  khetscore       NUMERIC NOT NULL,        -- CSV: Khetscore
  treatment       TEXT NOT NULL,           -- 'treat1' / 'treat2'
  sim_completed   BOOLEAN NOT NULL DEFAULT FALSE,
  completed_at    TIMESTAMPTZ NULL,        -- timestamp when simulation completed
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_farmers_treatment
  ON public.farmers(treatment);

CREATE INDEX idx_farmers_sim_completed
  ON public.farmers(sim_completed);

ALTER TABLE public.farmers ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Public can read farmers"
  ON public.farmers
  FOR SELECT
  USING (true);

CREATE POLICY "Public can insert farmers"
  ON public.farmers
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Public can update farmer completion"
  ON public.farmers
  FOR UPDATE
  USING (true)
  WITH CHECK (true);
